### ISSUE TITLE
License/copyright is missing

### ISSUE THREAD

**Issue by Pospelove** [d1vanov/Simple-FFT#4]
Please add LICENSE.md so Simple-FFT could be added to vcpkg (https://github.com/microsoft/vcpkg/issues/11928).

**Comment by d1vanov** [comment]
I'm quite surprised this library has become so popular that someone suggested to add it to vcpkg. Ok then, I changed the license from beerware to MIT as it seems fitting and respectable enough.

**Comment by Pospelove** [comment]
Thanks a lot :)
